### PR TITLE
Added most functionality from the salt formula

### PR DESCRIPTION
**Pull request by p-thurner**
- renamed to role-letsencrypt (before: role-certbot)
- detect if this is the first time a certificate is requested and run standalone
- setup a cronjob shell script with hooks
- remove package maintainer cronjob (lacks hooks and bugs around)
- allow for enforced execution of the shell script for renewal via ansible-playbook

### CODE REVIEW

**Comment by p-thurner** [comment]
maybe also fix #7

**Comment by baccenfutter** [comment]
@p-thurner 

I don't understand what is happening here? Why exactly are you not simply using `blunix.role-certbot`? It is working perfectly fine. Now we have two roles for LetsEncrypt and I don't really see the point of that.

```yaml
- hosts: all
  become: yes
  roles:
    - blunix.role-certbot
  post_tasks:
    - name: creating certificate
      command: certbot certonly -d example.com
```

This little snippet covers the entire process. It even automagically installs the cron-job for renewal. So, what exactly justifies a second role for LetsEncrypt?

**Comment by p-thurner** [comment]
> Why exactly are you not simply using blunix.role-certbot

This is role-certbot (I renamed it). I found this solution (creating the cronjob oneself) better as sometimes you want hooks, like concatinating certs for haproxy, gitlab-ctl reconfigure, nginx restart or similar.

**Comment by baccenfutter** [comment]
Why reinvent the wheel? https://certbot.eff.org/docs/using.html#pre-and-post-validation-hooks

**Comment by p-thurner** [comment]
feel free to change to using that

**Comment by baccenfutter** [comment]
What do you mean? That's exactly what it was using before your PR:

```yaml
- file:
    src: here/and/there
    dest: /etc/letsencrypt/.../hooks/post_hook.sh
    mode: 0700
```

This might be a good example why discussing changes in issues before investing time and opening pull-requests often makes a lot of sense.

**Pull request closed without merging**
